# Generated by Django 2.1.1 on 2020-03-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200327_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
    ]
