# Generated by Django 2.1.1 on 2020-03-27 12:11

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200327_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 12, 11, 32, 361934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
